<?php
require_once "config.php";
require_once 'session.php';

//$infos[] = "Un message d'information";
//$erreurs[] = "Un message d'erreur";
?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <?php require_once 'section/head.phtml' ?>
    <title>Accueil - Point final</title>
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>

    <div>
        <?php require_once 'section/retroaction.phtml'; ?>

        Vous n'êtes pas obligé de prendre cette structure de page... vous êtes libre de faire comme vous le voulez.
    </div>

    <?php require_once 'section/pied.phtml'; ?>
</body>

</html>